### ISSUE TITLE
Samples using with Web API Odata  ?

### ISSUE THREAD

**Issue by victorperez2911** [danderson00/DynamicOData#1]
Great idea, but little documented.

How would this class be used in an ODataController's Framework Web API?

The methods that target OData normally return  `IQueryable <Type>`, therefore, as its example, what to put in the generic Type?

**Comment by srinivasupadhya** [comment]
see if [this](https://github.com/TrevorPilley/MicroLite.Extensions.WebApi.OData/blob/19d9d310d0f31d15e08710e9cd20d73654800666/MicroLite.Extensions.WebApi.OData/MicroLiteODataApiController%7BTEntity%2CTEntityKey%7D.cs#L270) helps
